### PR TITLE
Seperate schema and (custom) error messages

### LINKED ISSUE #56: Schema validation does not work in monaco editor
__Describe the Bug__

When using this schema with the monaco editor and enabling validation, certain errorMessages throw JS exceptions in the dev console.

__Steps to Reproduce__

1. Goto https://672q2q.csb.app/ (source code available here: https://codesandbox.io/s/element-templates-validation-monaco-672q2q?file=/src/index.js)
2. Hover over the version warning
3. Observe that the error message is correctly displayed
4. Hover over the documentationRef warning
5. Observe that the error message is not displayed
6. Check the browser console error log to see that an exception is thrown.

```text
errors.ts:22 Uncaught Error: t.message.replace is not a function

TypeError: t.message.replace is not a function
    at g (markers.ts:151:35)
    at Object.u [as makeKey] (markers.ts:123:10)
    at v.renderMarkerStatusbar (markerHoverParticipant.ts:188:86)
    at v.renderHoverParts (markerHoverParticipant.ts:101:8)
    at Bi._renderMessages (contentHover.ts:228:33)
    at Bi._withResult (contentHover.ts:193:9)
    at contentHover.ts:65:9
    at invoke (event.ts:554:17)
    at o.fire (event.ts:721:15)
    at b._fireResult (hoverOperation.ts:160:18)
    at b._setState (hoverOperation.ts:104:9)
    at b._triggerSyncComputation (hoverOperation.ts:144:8)
    at l.runner (hoverOperation.ts:62:89)
    at l.doRun (async.ts:503:9)
    at l.onTimeout (async.ts:497:9)
    at errors.ts:22:12
```

__Expected Behavior__

All error messages should work correctly.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 102
- OS: Windows 10
- Library version: 0.4.1

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #56 

* Exports custom `errorMessages` under 
  * `@camunda/element-templates-json-schema/resources/error-messages.json`
  * `@camunda/zeebe-element-templates-json-schema/resources/error-messages.json`
* removes `errorMessage` keyword from both `schema.json` files

Examples of how to consume the `error-message.json` on top:
* Our JS validator: https://github.com/bpmn-io/element-templates-validator/pull/10
* Our schema test suite: https://github.com/camunda/element-templates-json-schema/pull/57/commits/2629349b4c4e05b31f5fdd6b0dc9a0f65991f006

image

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
That's a proposal and I'm open to discussing this. The goal shall be in any case to remove the `errorMessage` keyword from our base schemas (cf. https://github.com/camunda/element-templates-json-schema/issues/56#issuecomment-1144898034)

**Comment by pinussilvestrus** [comment]
This is ready for review now.

**Comment by barmac** [comment]
I will have a look.

**Review by barmac — APPROVED** [review]

**Comment by barmac** [comment]
Great job!

**Comment by pinussilvestrus** [comment]
I will release a new alpha version and[ tell in the issue](https://github.com/camunda/element-templates-json-schema/issues/56) which schema to use for Monaco 👍

**Pull request merged**
