### PR TITLE
C7 group properties

### PR DESCRIPTION
**Pull request by pinussilvestrus**
This adds JSON schema support for the new `groups` feature.

Related to https://github.com/camunda/camunda-modeler/issues/2673

### CODE REVIEW

**Review by MaxTru — COMMENTED** [review]
Would it also be possible to validate that a referenced group must exists in the `#/groups`?

**Comment by pinussilvestrus** [comment]
Maybe this can be achieved with a `if-then` rule, but I'd have to double-check it (next week probably)

But would be nice though 👍

**Comment by MaxTru** [comment]
> Maybe this can be achieved with a `if-then` rule, but I'd have to double-check it (next week probably)
> 
> But would be nice though +1

If it poses like more than 2hour efforts, I think we shouldn't do it (my opinion, you decide :-) ). I would see this as a cherry on top.

**Comment by pinussilvestrus** [comment]
I gave it a Sunday afternoon try, but without luck. Maybe that's something not well supported via JSON Schema by now (we use `draft-07`). I opened an issue for that with a sketch I could imagine how it works: https://github.com/camunda/element-templates-json-schema/issues/40

**Review by MaxTru — APPROVED** [review]

**Pull request merged**
