### PR TITLE
Prepare release

### LINKED ISSUE #42: Prepare project to provide two packages
__What should we do?__

It should be possible to release the two schemas separately from each other (e.g. by using `lerna`). In fact, this repo should be transformed to a monorepo, providing to packages, e.g.

* `@camunda/element-templates-json-schema@0.7.0/resources/schema.json`
* `@camunda/zeebe-element-templates-json-schema@0.1.0/resources/schema.json`

__Why should we do it?__

Child of https://github.com/bpmn-io/bpmn-js-properties-panel/issues/561

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #42

-----

* Re-structure project in two packages, using `lerna`
  * `@camunda/element-templates-json-schema`
  * `@camunda/zeebe-element-templates-json-schema`
* Prepares releases
  * `@camunda/element-templates-json-schema@0.7.0`
  * `@camunda/zeebe-element-templates-json-schema@0.1.0`
* Make sure we version the schemas independently (cf. https://github.com/camunda/element-templates-json-schema/pull/43/commits/a4e3b2f73c7bf841b473514976e258ea9783622d)

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
I thought about it but didn't consider it yet since there is no properties panel element templates feature that would support it as of now. 

However, in the sense of a "shared" package, as we have it in dmn-js, it actually makes sense. So I think I will add it on top inside this PR. Thanks for mentioning :+1:

**Comment by pinussilvestrus** [comment]
I added it accordingly (https://github.com/camunda/element-templates-json-schema/pull/43/commits/40f2c63e476ec16dabbaaa70e671c28b5f654c51). What I came up with there is to move the shared (base) definitions to another package `@camunda/element-templates-json-schema-shared`. 

What it does not deliver is a standalone, own schema export. The `property.binding` definitions are handled by the two main schema files, the base properties don't include them - since JSON schema doesn't support inheritance very well.

If we really see the necessity for a base element template schema export, we could add it later on top. :+1:

**Comment by pinussilvestrus** [comment]
@barmac @philippfromme maybe you can give this one a review? It's basically blocking other, downstream PRs 🙂

**Comment by philippfromme** [comment]
Yes, I was planning to look into it today.

**Review by philippfromme — APPROVED** [review]
Good job! 🚀

**Pull request merged**
