### PR TITLE
`FIX`: revert broken condition rules

### PR DESCRIPTION
**Pull request by marstamm**
This reverts https://github.com/camunda/element-templates-json-schema/pull/128

related to https://github.com/camunda/element-templates-json-schema/issues/133

### CODE REVIEW

**Comment by marstamm** [comment]
Consider the fix instead ==> https://github.com/camunda/element-templates-json-schema/pull/135

**Comment by marstamm** [comment]
Reopening as https://github.com/camunda/element-templates-json-schema/pull/135 does not fix all problems

**Comment by barmac** [comment]
Let's consider replacing this PR with https://github.com/camunda/element-templates-json-schema/pull/136

**Comment by marstamm** [comment]
Superseded by https://github.com/camunda/element-templates-json-schema/pull/136

**Pull request closed without merging**
