### PR TITLE
feat: export precompiled validator with ajv

### PR DESCRIPTION
**Pull request by barmac**
Related to https://github.com/camunda/camunda-modeler/issues/2181

### CODE REVIEW

**Comment by barmac** [comment]
TODO: add a validator as a stateless service implementing interface of https://github.com/bpmn-io/json-schema-validator

**Comment by pinussilvestrus** [comment]
That's awesome @barmac 👍

**Comment by pinussilvestrus** [comment]
I wonder whether the new precompiled validator could also expose the used Schema, so we would [get rid of this](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L8-L11) and also make the versioning validation possible in the properties panel.

**Comment by barmac** [comment]
I believe we could just expose the supported schema version via a static property.

**Comment by barmac** [comment]
Closed in favor of https://github.com/bpmn-io/element-templates-validator

**Pull request closed without merging**
